apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zookeeper
  namespace: weather-infra
spec:
  project: default
  source:
    repoURL: https://github.com/Nimrod-s-weather-app/weather-infra.git
    targetRevision: main
    path: k8s/zookeeper
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
